lib: [
  "_build/install/default/lib/hflmc2/META" {"META"}
  "_build/install/default/lib/hflmc2/hflmc2.a" {"hflmc2.a"}
  "_build/install/default/lib/hflmc2/hflmc2.cma" {"hflmc2.cma"}
  "_build/install/default/lib/hflmc2/hflmc2.cmi" {"hflmc2.cmi"}
  "_build/install/default/lib/hflmc2/hflmc2.cmt" {"hflmc2.cmt"}
  "_build/install/default/lib/hflmc2/hflmc2.cmx" {"hflmc2.cmx"}
  "_build/install/default/lib/hflmc2/hflmc2.cmxa" {"hflmc2.cmxa"}
  "_build/install/default/lib/hflmc2/hflmc2.cmxs" {"hflmc2.cmxs"}
  "_build/install/default/lib/hflmc2/hflmc2.dune" {"hflmc2.dune"}
  "_build/install/default/lib/hflmc2/hflmc2.ml" {"hflmc2.ml"}
  "_build/install/default/lib/hflmc2/opam" {"opam"}
]
bin: [
  "_build/install/default/bin/hello_world" {"hello_world"}
]
